#!/usr/bin/env bash
confirm() {
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        *)
            exit 1
            ;;
    esac
}

VER=$1

if [ "$VER" = "" ]; then
               echo "please provide a version number"
               exit 1;
            fi

echo $VER
head package.json
git status        
confirm "Have you incremented package.json to version number $VER?" &&
confirm "Confirm add package.json and package-lock.json to git and push tags?" &&
confirm "Are you on master branch?" &&
cp .env.testnet-prod .env.production
echo "updated production .env"
npm run build
echo "built"
ssh root@geth-noordung.fairdatasociety.org -N -L 2000:127.0.0.1:8500 & echo $! > /tmp/fairdrop-sshpid
echo "waiting for ssh tunnel"
while ! nc -z localhost 2000; do   
  sleep 0.1 # wait for 1/10 of the second before check again
done
echo "uploading to https://geth-noordung.fairdatasociety.org/"
swarm --bzzapi http://localhost:2000/ --defaultpath index.html --recursive up ~/Code/df/fairdrop/build/ > current_live
sleep 5
HASH=`cat config.txt`
echo "uploaded to hash $HASH"
git add package.json package-lock.json && git commit -m "bump version"
echo "added bump version"
git add current_live && git commit -m 'bump current_live'
echo "added bump current_live"
git tag $VER
echo "added tag $VER"
git push origin $VER
git push df $VER
cat current_live
kill $(cat /tmp/fairdrop-sshpid)