#!/usr/bin/env bash
confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        *)
            exit 1
            ;;
    esac
}

VER=$1

if [ "$VER" = "" ]; then
               echo "please provide a version number"
               exit 1;
            fi
echo $VER
head package.json
git status            
confirm "Have you incremented package.json to version number $VER?" &&
confirm "Is the stage otherwise clean?" &&
confirm "Are you on staging branch?" &&
git add package.json && git commit -m "bump version"
echo "added bump version"
git tag $VER
echo "added tag $VER"
git push origin $VER
git push df $VER
echo "pushed"
cp .env.testnet-dev .env.production 
echo "updated production .env"
npm run build
echo "built"
echo "now upload to swarm"
echo "'./swarm --bzzapi http://209.97.190.111:8500/ --defaultpath index.html --recursive up ~/Code/df/fairdrop/build/'"
echo "and then change ENS reference"
echo "and change the current_live file"
echo "and change the ENS reference"