#!/usr/bin/env bash
confirm() {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case "$response" in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        *)
            exit 1
            ;;
    esac
}

VER=$1

if [ "$VER" = "" ]; then
               echo "please provide a version number"
               exit 1;
            fi

echo $VER
head package.json
git status        
confirm "Have you incremented package.json to version number $VER?" &&
confirm "Is the stage otherwise clean?" &&
confirm "Are you on master branch?" &&
echo "pushed"
cp .env.testnet-prod .env.production 
echo "updated production .env"
npm run build
echo "built"
echo "uploading to http://178.128.196.190:8500/"
swarm --bzzapi http://178.128.196.190:8500/ --defaultpath index.html --recursive up ~/Code/df/fairdrop/build/ > current_dev
HASH=`cat config.txt`
echo "uploaded to hash $HASH"
git add package.json package-lock.json && git commit -m "bump version"
echo "added bump version"
git add current_live && git commit -m 'bump current_dev'
echo "added bump current_dev"
git tag $VER
echo "added tag $VER"
git push origin $VER
git push df $VER
cat current_dev